import { Link } from "preact-router/match";
import usersJson from "../assets/data/users.json";

const Post = ({ post }) => {
  const poster = usersJson.find((p) => p.username === post.username);

  // Days ago generated by ChatGPT
  const postDate = new Date(post.date);
  const currentDate = new Date();

  const differenceInTime = currentDate.getTime() - postDate.getTime();
  const differenceInDays = Math.floor(differenceInTime / (1000 * 3600 * 24));

  const timeAgo =
    differenceInDays === 0 ? "Today" : `${differenceInDays} days ago`;

  return (
    <div>
      <div class="card">
        <div class="card-body row">
          <div class="col-1">
            <Link
              class="text-decoration-none"
              activeClassName="active"
              href={`/profile/${post.username}`}
            >
              <img
                src={poster.profilepic}
                style="width:100%;aspect-ratio:1/1;object-fit:cover;"
                alt={post.username}
              />
            </Link>
          </div>
          <div class="col">
            <Link
              class="text-decoration-none"
              activeClassName="active"
              href={`/profile/${post.username}`}
            >
              <h5 class="card-title">
                {poster.firstname} {poster.lastname}
                <span class="text-muted"> @{post.username}</span>
              </h5>
            </Link>
            <h6 class="text-muted">{timeAgo}</h6>
            <p class="card-text">{post.content}</p>

            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <a href="#" class="float-end mx-1 btn">
                  <h5>❤️</h5>
                </a>
                <a href="#" class="float-end mx-1 btn">
                  <h5>🔁</h5>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <hr />
    </div>
  );
};

export default Post;
